name: angular2-examples
dependencies:
  angular2: 2.0.0-beta.1
transformers:
- angular2:
    entry_points: site/hello-world/app.dart
- $dart2js:
    minify: true
    commandLineOptions:
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives
    - --enable-experimental-mirrors
